In [1]:
import numpy as np

In [83]:
# Crear un vector de ceros de tamaño 10

In [4]:
vector_zeros = np.zeros(10)

In [6]:
print(vector_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [84]:
#Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [7]:
vector_zeros[5]=1

In [8]:
print(vector_zeros)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [85]:
# Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.


In [10]:
vector_cincuenta = np.arange(50)

In [11]:
print(vector_cincuenta)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [18]:
alRevez= vector_cincuenta[::-1]

In [19]:
alRevez

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [86]:
# Crear una matriz de 3 x 3 con valores del cero al 8

In [26]:
matriz_zero_al_ocho = np.arange(9).reshape(3,3)
matriz_zero_al_ocho

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Encontrar los indices que no sean cero en un arreglo


In [30]:
arreglo = np.array([1,2,0,0,4,0])
arreglo2 = arreglo > 0
arreglo[arreglo2]

array([1, 2, 4])

In [ ]:
#  Crear una matriz de identidad 3 x 3

In [35]:
matriz_identidad = np.identity(3)

In [36]:
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Crear una matriz 3 x 3 x 3 con valores randomicos

In [44]:
matriz_randomicos = np.random.rand(3,3,3)
matriz_randomicos

array([[[0.01433158, 0.7903003 , 0.13821173],
        [0.1872256 , 0.40961398, 0.99806351],
        [0.09691419, 0.65625664, 0.60940396]],

       [[0.90455731, 0.54225902, 0.19564919],
        [0.92130317, 0.31147394, 0.56530222],
        [0.03749058, 0.05699613, 0.97018713]],

       [[0.89702448, 0.84433677, 0.15568645],
        [0.55296046, 0.57242927, 0.39579656],
        [0.94854946, 0.04607351, 0.13172041]]])

In [87]:
# Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [91]:
matriz_diez_por_diez = np.random.rand(10,10)
matriz_diez_por_diez
maximo= np.max(matriz_diez_por_diez)
print(f"este es maximo",maximo)
minimo= np.min(matriz_diez_por_diez)
print(f" este es minimo",minimo)


este es maximo 0.9932982132973608
 este es minimo 0.007840223848811223


In [92]:
# ¿Como crear una serie de una lista, diccionario o arreglo?

In [47]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
serie_de_lista = pd.Series((mylist,myarr,mydict))

In [93]:
serie_de_lista

0    [a, b, c, e, d, f, g, h, i, j, k, l, m, n, o, ...
1    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...
2    {'a': 0, 'b': 1, 'c': 2, 'e': 3, 'd': 4, 'f': ...
dtype: object

In [94]:
# ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [53]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
indice_serie_a_columna= pd.Series((mylist))

In [54]:
indice_serie_a_columna

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [96]:
#¿Como combinar varias series para hacer un DataFrame?

In [61]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
result0 ={'letras' :ser1 , 'num':ser2}
combinar_series_dataFrame = pd.DataFrame(result0) 

result

letras  num
0       a    0
1       b    1
2       c    2
3       e    3
4       d    4
5       f    5
6       g    6
7       h    7
8       i    8
9       j    9
10      k   10
11      l   11
12      m   12
13      n   13
14      o   14
15      p   15
16      q   16
17      r   17
18      s   18
19      t   19
20      u   20
21      v   21
22      w   22
23      x   23
24      y   24
25      z   25

In [97]:
# Como obtener los items que esten en una serie A y no en una serie B?

In [66]:
ser1 = set(pd.Series([1, 2, 3, 4, 5]))
ser2 = set(pd.Series([4, 5, 6, 7, 8]))
items_X = ser1-ser2
items_X



{1, 2, 3}

In [98]:
# ¿Como obtener los items que no son comunes en una serie A y serie B?

In [108]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

series_unidas = ser2 = ser1

series_unidas



0    1
1    2
2    3
3    4
4    5
dtype: int64

In [99]:
#¿Como obtener el numero de veces que se repite un valor en una serie?


In [68]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()


g    6
h    4
b    4
d    4
f    3
e    3
a    3
c    3
dtype: int64

In [100]:
#Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

In [112]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
cuantor_hay_items = ser.value_counts()
cuantor_hay_items



2    4
4    3
3    3
1    2
dtype: int64

In [117]:
#¿Como transformar una serie de un arreglo de numpy a un DataFrame con un shape definido?


In [119]:
ser = pd.Series(np.random.randint(1, 10, 35))
numpy = pd.DataFrame(ser)
numpy

0
0   5
1   8
2   8
3   2
4   3
5   8
6   9
7   6
8   6
9   8
10  7
11  6
12  1
13  8
14  3
15  9
16  9
17  6
18  9
19  6
20  9
21  6
22  6
23  9
24  3
25  6
26  7
27  5
28  2
29  7
30  5
31  8
32  6
33  8
34  5

In [109]:
#¿Obtener los valores de una serie conociendo la posicion por indice?
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [103]:
#¿Como anadir series vertical u horizontalmente a un DataFrame?


In [121]:
ser1 = set(pd.Series(range(5)))
ser2 = set(pd.Series(list('abcde')))

result0 ={'letras' :ser1 , 'num':ser2}
combinar_series_dataFrame = pd.DataFrame(result0) 

result

letras  num
0       a    0
1       b    1
2       c    2
3       e    3
4       d    4
5       f    5
6       g    6
7       h    7
8       i    8
9       j    9
10      k   10
11      l   11
12      m   12
13      n   13
14      o   14
15      p   15
16      q   16
17      r   17
18      s   18
19      t   19
20      u   20
21      v   21
22      w   22
23      x   23
24      y   24
25      z   25

In [104]:
#¿Obtener la media de una serie agrupada por otra serie?

In [105]:
# ¿Como importar solo columnas especificas de un archivo csv?

In [ ]:
CSV_PATH = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
import requests
import io
s=requests.get(CSV_PATH).content


